### ISSUE TITLE
[Request] Essential Oil Diffusor

### ISSUE THREAD

**Issue by DJay-X** [codetheweb/homebridge-tuya#1]
@codetheweb First of all, thanks for your great work and sharing.
Thanks to your Plugin and the instructions I was able to easily integrate my [Oittm Brand Essential Oil Diffusor](https://amzn.to/2MrvcbO) to HomeKit.
As I understand there are many Manufacturers with different names that are using the Tuya Cloud API Services, such as the Company Oittm does.

Is there a way to get the Diffusor working with your plugin not just as an on/off switch as it does at the moment? More like mybe a fan including intensity and LED light? This would be awesome.

If there is anything I can do to help investigate, maybe information from the link-wizard, please of course let me know.

Thanks again,
Daniel

![napkin 16 08 18 1 35 18 pm](https://user-images.githubusercontent.com/3874239/44207604-36038c00-a15e-11e8-8c16-442776111f9e.png)

![napkin 16 08 18 1 01 56 pm](https://user-images.githubusercontent.com/3874239/44207622-4ca9e300-a15e-11e8-902a-0e55fbb3deb0.png)

**Comment by codetheweb** [comment]
Ok, closing this issue for now.  I will notify you if support is added for diffusers.
