### ISSUE TITLE
Issue following Setup Instructions to retrieve Tuya API

### ISSUE THREAD

**Issue by xepicjoshx** [codetheweb/homebridge-tuya#15]
Hello, 

I am attempting to follow the Setup Instructions but the website looks different and the only thing that looks close to the "New App" option requires a $1500 payment. 

I just purchased two switches that are TUYA compatible and wanted to have this setup before they arrive. 

Any ideas how I can retrieve my API credentials?

**Comment by codetheweb** [comment]
This is a known issue.  Tuya recently changed their website.  I'm currently working on an alternative setup process, follow this [issue](https://github.com/codetheweb/tuyapi/issues/91) for updates.

**Comment by xepicjoshx** [comment]
Is it possible to use the deprecated instructions or maybe reach out to Tuya?

**Comment by codetheweb** [comment]
Yes, the deprecated instruction still work fine.

I've finished the new setup method and now I'm just getting it ready for release.  It should be available by the end of the weekend.

**Comment by mikeyis** [comment]
Hey! Any update on the new release please?? I just bought 6 more switches and can't set them up :(

**Comment by codetheweb** [comment]
Sorry, forgot to update people here.  The link in the README now goes to an updated page [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md).
