### ISSUE TITLE
Is possible add this device?

### ISSUE THREAD

**Issue by kalety** [codetheweb/homebridge-tuya#26]
Hi!, i've recently buy one outlet that have a RGB LED light too. With the API only I get on/off the outlet part. Were possible add this devices?. I've put in the config.json several "dps's" but no success.

This is the node script's output:

Both LED light and outlet OFF

{ devId: '00153632807d3a796b43',
  dps: 
   { '1': false,
     '27': false,
     '28': 'colour',
     '29': 255,
     '31': 'f000ff012864ff',
     '32': '3855b40168ffff',
     '33': 'ffff500100ff00',
     '34': 'ffff8003ff000000ff000000ff000000000000000000',
     '35': 'ffff5001ff0000',
     '36': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000' } }

Both LED light and outlet ON (color magenta)

{ devId: '00153632807d3a796b43',
  dps: 
   { '1': true,
     '27': true,
     '28': 'colour',
     '29': 255,
     '31': 'f000ff012864ff',
     '32': '3855b40168ffff',
     '33': 'ffff500100ff00',
     '34': 'ffff8003ff000000ff000000ff000000000000000000',
     '35': 'ffff5001ff0000',
     '36': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000' } }

LED ON and outlet OFF:

{ devId: '00153632807d3a796b43',
  dps: 
   { '1': false,
     '27': true,
     '28': 'colour',
     '29': 255,
     '31': 'f000ff012864ff',
     '32': '3855b40168ffff',
     '33': 'ffff500100ff00',
     '34': 'ffff8003ff000000ff000000ff000000000000000000',
     '35': 'ffff5001ff0000',
     '36': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000' } }

LED OFF and outlet ON:

{ '1': true,
     '27': false,
     '28': 'colour',
     '29': 255,
     '31': 'f000ff012864ff',
     '32': '3855b40168ffff',
     '33': 'ffff500100ff00',
     '34': 'ffff8003ff000000ff000000ff000000000000000000',
     '35': 'ffff5001ff0000',
     '36': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000' } }

Thanks in advance!

**Comment by kalety** [comment]
I've get writing this in config.json, turn on/off LED and switch alone or together....

{
                    "name": "Enchufe Luz",
                    "id": "00153632807d3a796b43",
                    "key": "b2c62dd97417f483",
                    "ip": "192.168.1.75",
                    "options": {
                        "dps": 1
                    }
                },
                {
                    "name": "LED enchufe",
                    "id": "00153632807d3a796b43",
                    "key": "b2c62dd97417f483",
                    "ip": "192.168.1.75",
                    "options": {
                        "dps": 27
                    }
                },

**Comment by codetheweb** [comment]
That's interesting, I've never heard of a device like that.  Mind linking to where you bought it from?

Brightness controls have been added; you can use them by setting `type` to `dimmer` (see README).

RGB controls still have not been added, I'll mention you in the main issue for that so you'll be notified when support is added.

**Comment by kalety** [comment]
Here is the link:
https://www.amazon.es/gp/product/B07GH7XRB5/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1

**Comment by kalety** [comment]
Thanks for your support!
