### ISSUE TITLE
Not able to turn socket on/off but can still view status in Home app.

### ISSUE THREAD

**Issue by charlesomer** [codetheweb/homebridge-tuya#27]
I have been able to set up Homebridge on my Raspberry Pi Zero W which seems to be working correctly. However, I am unable to change the status of the smart sockets I have added via homebridge-tuya. I can see the status of the socket via the Home app and it appears to be able to communicate with Homebridge correctly but I just can't change their status via the Home app.

I have run Homebridge with debug=* and by the looks of the logs, Homebridge attempts to send the http request but the connection closes seemingly without error, timeout waiting for response.

I have also tried adding a static IP which just produces the same result.

`Nov 25 17:23:40 RaspberryPiZeroW homebridge[746]: 2018-11-25T17:23:40.356Z TuyAPI Send attempt 5
Nov 25 17:23:40 RaspberryPiZeroW homebridge[746]: 2018-11-25T17:23:40.362Z TuyAPI Sending this data: 000055aa000000000000000700000087332e316464386134616162643735653739633152544970324a3170694a5533364271644f2b62567244514a506d386675315741426a6f6f6d4a2b52313461776633724254757247716271312f5842704151493474514c6c366c6874575a615450654f44307970544d4b764b7633362f457442575a6763735639717a306f413d000000000000aa55
Nov 25 17:23:40 RaspberryPiZeroW homebridge[746]: 2018-11-25T17:23:40.364Z TuyAPI Connect 192.168.0.9
Nov 25 17:23:40 RaspberryPiZeroW homebridge[746]: 2018-11-25T17:23:40.494Z TuyAPI Socket connected.
Nov 25 17:23:45 RaspberryPiZeroW homebridge[746]: Sun, 25 Nov 2018 17:23:45 GMT Accessory [Homebridge] Error setting Characteristic "On" to value 1:  Timeout waiting for response
Nov 25 17:23:45 RaspberryPiZeroW homebridge[746]: Sun, 25 Nov 2018 17:23:45 GMT EventedHTTPServer [::ffff:192.168.0.14] HTTP Response is finished
Nov 25 17:23:45 RaspberryPiZeroW homebridge[746]: 2018-11-25T17:23:45.413Z TuyAPI Socket closed: 192.168.0.9`

**Comment by codetheweb** [comment]
TuyAPI should retry a few times.  Is there more to the log?

This type of behavior is usually a result of the correct ID but the wrong key.  How did you get those parameters?

**Comment by charlesomer** [comment]
Yeah I think it retries 5 times. I'll have another look later today and post more of the log.

I thought this was the case too but I tried re-adding the keys and IDs but the same issue occurred. I could be using the wrong values? I used Wireshark to monitor the IP address of the smart sockets which shows what looks like an ID and a key field. I'll upload the results from this later too.

**Comment by codetheweb** [comment]
Oh, that might be why it's not working.  Try following [this guide](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) to get the ID and keys.  Probably similar to what you were trying to do with Wireshark.

**Comment by charlesomer** [comment]
Yeah I’ve seen that guide before and attempted it but it wouldn’t work at the time - I’ll give it another go though later.

I was hoping the ID and Keys would be the same whether they were accessed via Wireshark or that method. Perhaps I don’t need to include the entire Key as it looks like the first part is the same for both sockets?

Are the keys the same length/format for all smart devices?

**Comment by codetheweb** [comment]
Both ID and keys should be the same length for all types of devices.

If the key that you're seeing is partly the same for both of your devices, it's most likely the `productKey` - which is just an internal identifier for the manufacturer.  You want the `localKey` field.  Sorry about the confusion, should probably be in the docs somewhere.

**Comment by GioCirque** [comment]
When you tried the method described, did you enable SSL on the proxy and install the root certificate on your device?

**Comment by charlesomer** [comment]
I have set the certificate on my laptop to "Always trust" and I have installed the certificate on my phone too. As well as set up the proxy with the values provided when running `tuya-cli list-app` on my phone.

**Comment by codetheweb** [comment]
You don't need to trust the certificate on your laptop.  Try loading a HTTPS site on your phone, it should work if everything is configured properly.

It's not possible to get the parameters from an encrypted Wireshark session.

**Comment by charlesomer** [comment]
I can access https://www.google.com but I get a warning about the certificate not being trusted. I have installed the proxy certificate and it say's it's verified in iOS.

**Comment by codetheweb** [comment]
Glad you got it working.

I don't have any plans to make a video, although I'll happily accept a PR for a link to one.

The process could be slightly improved (`tuya-cli` should generate the certificate directly without having to mess around with AnyProxy), but I think this may be the best solution for now.  If you have a better idea, I'm very open to hearing it.

**Comment by charlesomer** [comment]
Hmm I don't know enough about how the localKey is detected/decrypted at the moment but I might have a look if I get time at some point.
