### ISSUE TITLE
Device disappears when not connected to power and Homebridge was restarted

### ISSUE THREAD

**Issue by DJay-X** [codetheweb/homebridge-tuya#3]
@codetheweb Hi again and I hope not to bother.
I noticed with my device "Essential Oil Diffusor" that when it is disconnected from the power, what is the case regularly, that is not longer shown in HomeKit (Home App, Eve) when Homebridge is restarted. 
After connecting the Device back to power and restart Homebridge again, the Device is also showing up in the default room. 
This would be great if it could be fixed to display the device permanently. 

Thank you very much for you time and support.

**Comment by codetheweb** [comment]
This was intended to be a feature and not a bug, although I can see now that I didn't really think it through.

I'll do some testing on Monday, but for now passing in an IP to your `config.json` should do the trick.

**Comment by codetheweb** [comment]
Hey, sorry I haven't updated this for a few days (I'm leaving for college tomorrow and have been very busy).  I can't promise that this will be resolved in the next few days, but hopefully I'll get to it within a month or so.

Did passing an IP work?

**Comment by DJay-X** [comment]
Hi @codetheweb Thanks. The IP Workaround helped a lot. 
Today I also noticed an update to v0.1.3 an I will give this of course also a try.
Thanks again. 

All the best for your college work but hopefully we see more of your homebridge development in the future. 👍🏻

**Comment by codetheweb** [comment]
Thanks. 

V0.1.3 probably won't fix it. I'll try to look at this in the next few days.

**Comment by DJay-X** [comment]
@codetheweb Just want to let you know, with V0.1.3 the Essential Oil Diffuser didn't respond anymore. The switch in HomeKit didn't show an error but the the device just didn't do anything.
Back to V0.1.2 without changing anything else it worked again reliably. 
So I keep with V0.1.2 including the IP for while. 😉

**Comment by codetheweb** [comment]
That's strange, nothing I changed should have affected that.  Would you mind updating the plugin again and running `DEBUG=* homebridge`?  It also might help if you delete the `persist/` and `accessories/` folders in your Homebridge folder (the place where your `config.json` is stored).

**Comment by codetheweb** [comment]
Any luck @DJay-X?

**Comment by DJay-X** [comment]
Sorry for my late reply. Time flies. ...
I deleted the accessories folder and that fixed the problem. Updating to you plugin Version V0.1.3 and the Smart Oil Diffusor is still working fine, even after a few days off of power and reconnected today. 
Thanks again. 👍🏻

**Comment by codetheweb** [comment]
Glad it's working now.

**Comment by tomky** [comment]
Wondering if this is resolved when we didn’t set an IP here? I think the typical behavior in homebridge is that when you configure an object in configuration, it will stay in HomeKit until it is removed from config.json. The object could be in disconnection status if it is gone (like power off), but it is still there. This behavior helps preserve the home automations so we don’t need to setup all over again whenever the plug is off the wall.

**Comment by codetheweb** [comment]
@tomky 

The (issue?) experienced by @DJay-X is that if you don't pass in an IP to the config and the device is offline, TuyAPI fails to find the device on the network resulting in it not showing up in HomeKit until the device is back online and Homebridge is restarted.

**Comment by tomky** [comment]
Maybe my issue is different. Sometimes my Tuya plug may be unplugged by others, and then the device will be disconnected from homebridge, which is fine. But if somehow the homebridge restart when the plug is unplugged, the device will be removed from the homebridge, and all related automation will be deleted. 

Even if I plug it back and restart the homebridge, it will back online but as a new device in the default room. So everytime this happens, I need to rebuild the automation all over again.

**Comment by codetheweb** [comment]
@tomky HomeKit should retain the automation as the device always has the same internal UID...

Could you provide a Homebridge debug log where this is happening please?

**Comment by kylewhirl** [comment]
Could you reopen this?
