### ISSUE TITLE
TypeError: TuyaDevice is not a constructor

### ISSUE THREAD

**Issue by weiran** [codetheweb/homebridge-tuya#32]
Trying to add this plugin to my homebridge, but I get this error when starting up:

```
homebridge[7016]: (node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: TuyaDevice is not a constructor
```

I'm running latest version of homebridge, node, npm, homebridge-tyua etc. Any ideas on tracking down the error?

Here are the logs previous to that error:

```
homebridge[7288]: [2018-12-21 15:03:54] [TuyaPlatform] Initializing TuyaPlatform platform...
homebridge[7288]: [2018-12-21 15:03:54] [TuyaPlatform] Device has IP: 192.168.1.24
homebridge[7288]: [2018-12-21 15:03:54] [TuyaPlatform] New Device Online: Christmas Tree Lights (xxx)
homebridge[7288]: [2018-12-21 15:03:54] [TuyaPlatform] Adding: Christmas Tree Lights (generic / xxx)
homebridge[7288]: (node:7288) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: TuyaDevice is not a constructor
homebridge[7288]: (node:7288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js pro...
```

Thanks

**Comment by codetheweb** [comment]
What does your `config.json` for Homebridge look like?

**Comment by weiran** [comment]
```
"platforms": [
    {
      "platform": "TuyaPlatform",
      "name": "TuyaPlatform",
      "devices": [
        {
          "name": "Lights",
          "id": "abc",
          "key": "abc",
          "ip": "x.x.x.x"
        }
      ]
    }
  ]
}
```

**Comment by codetheweb** [comment]
Everything looks good there...

I would try deleting the `accessories/` and `persist/` directories in your Homebridge folder and see if that fixes the issue.

**Comment by weiran** [comment]
Still get the same error after deleting those folders. Any hints on debugging this?

**Comment by codetheweb** [comment]
How long is your `id` and `key`?  They should be 20 and 16 characters long respectively.

**Comment by weiran** [comment]
Yep, I've checked and they are those lengths.

**Comment by codetheweb** [comment]
Hmm, have you tried using [TuyAPI](https://www.npmjs.com/package/tuyapi) directly or the [CLI module](https://www.npmjs.com/package/@tuyapi/cli)?

**Comment by weiran** [comment]
Good idea, I'll give that a try.

**Comment by weiran** [comment]
The CLI module works, I can set the status of the switch. The problem seems to be that `require('tuyapi')` is returning an empty object, hence the error. This normally means there's a circular reference although I can't see how that's the case here. I'm running `homebridge-nest` plugin as well which works fine.

**Comment by codetheweb** [comment]
Given that the plugin works fine for other users, I'm guessing it's some issue with your configuration.

Do you have `tuyapi` installed globally?  If so, try uninstalling it.

Also try uninstalling and reinstalling `homebridge-tuya`.

**Comment by weiran** [comment]
Yeah after further investigation it probably is something to do with my specific env, I'll close this unless I find out anything different. Thanks for the help.

**Comment by codetheweb** [comment]
Ok, sorry I couldn't help more.

Let me know if you figure it out.
