### ISSUE TITLE
HomeKit - Cannot see devices

### ISSUE THREAD

**Issue by bengpearson** [codetheweb/homebridge-tuya#34]
Hello,

I've configured my config file as the following:

{
    "bridge": {
        "name": "Homebridge",
        "username": "XXXXXXXX",
        "port": XXXXXX,
        "pin": "XXX-XX-XXX"
    },

    "platform": "TuyaPlatform",
    "name": "TuyaPlatform",
    "devices": [{
            "name": "Media center",
            "id": "21138270807d3a6XXXXX",
            "key": "d8ae0a91cbe31XXX",
            "type": "Single Outlet",
            "ip": "10.0.1.22"

        },
        {
            "name": "Coffee machine",
            "id": "23468277ecfabc9XXXXX",
            "key": "9ed8385ec455dXXX",
            "type": "Single Outlet",
            "ip": "10.0.1.23"
        },
        {
            "name": "Kettle",
            "id": "23468277807d3a7XXXXX",
            "key": "b4479775c250XXXX",
            "type": "Single Outlet",
            "ip": "10.0.1.24"
        }
    ]
}

The config.json runs fine and links to my Home app on my iPhone. However, when I link the device while the room adds successfully it doesn't show any of my smart plugs (listed in the config file above). Adding the IP doesn't seem to make a difference. All of the plugs are working fine with TuyaSmart app and I've tried making DHCP reservations. All on the same SSID with no complicated rules.

Are you able to offer any assistance? Thanks!

![img_0464](https://user-images.githubusercontent.com/46249724/50651942-d414b900-0f7c-11e9-932d-16611ecf87bf.png)
![img_0465](https://user-images.githubusercontent.com/46249724/50651943-d414b900-0f7c-11e9-8c34-fe8ed3dfad07.png)

**Comment by codetheweb** [comment]
Your `type` parameter is wrong, for outlets it should be `generic`.

**Comment by bengpearson** [comment]
Hi,

Thanks for this - unfortunately same result. Tried the below with a fresh Homebridge username each time:

Tried changing type perameter to generic (same result)
Removed ip field as it's not in the basic config (same result)
Removed perameter field as not in the basic config (same result)

Any other suggestions?

**Comment by codetheweb** [comment]
What's the output of `DEBUG=* homebridge`?

**Comment by bengpearson** [comment]
pi@raspberrypi:~/.homebridge $ DEBUG=* homebridge
[03/01/2019, 18:38:32] Loaded config.json with 0 accessories and 0 platforms.
[03/01/2019, 18:38:32] ---
[03/01/2019, 18:38:32] Plugin /usr/local/lib/node_modules/homebridge-nefit-easy does not contain a package.json.
[03/01/2019, 18:38:34] Loaded plugin: homebridge-nefit-easy
[03/01/2019, 18:38:34] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[03/01/2019, 18:38:34] ---
[03/01/2019, 18:38:34] Loaded plugin: homebridge-tuya
[03/01/2019, 18:38:34] Registering platform 'homebridge-tuya.TuyaPlatform'
[03/01/2019, 18:38:34] ---
Load homebridge-tuya.TuyaPlatform
Setup Payload:

Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

  EventedHTTPServer Server listening on port 51826 +0ms
[03/01/2019, 18:38:34] Homebridge is running on port 51826.

**Comment by codetheweb** [comment]
I think I found the issue.

Your current config.json:

```javascript
{
"bridge": {
"name": "Homebridge",
"username": "XXXXXXXX",
"port": XXXXXX,
"pin": "XXX-XX-XXX"
},

"platform": "TuyaPlatform",
"name": "TuyaPlatform",
"devices": [{
        "name": "Media center",
        "id": "21138270807d3a6XXXXX",
        "key": "d8ae0a91cbe31XXX",
        "type": "Single Outlet",
        "ip": "10.0.1.22"

    },
    {
        "name": "Coffee machine",
        "id": "23468277ecfabc9XXXXX",
        "key": "9ed8385ec455dXXX",
        "type": "Single Outlet",
        "ip": "10.0.1.23"
    },
    {
        "name": "Kettle",
        "id": "23468277807d3a7XXXXX",
        "key": "b4479775c250XXXX",
        "type": "Single Outlet",
        "ip": "10.0.1.24"
    }
]

}
```

Proper config.json:

```javascript
{
   "bridge":{
      "name":"Homebridge",
      "username":"XXXXXXXX",
      "port":"XXXXXX",
      "pin":"XXX-XX-XXX"
   },
   "platforms":[
      {
         "platform":"TuyaPlatform",
         "name":"TuyaPlatform",
         "devices":[
            {
               "name":"Media center",
               "id":"21138270807d3a6XXXXX",
               "key":"d8ae0a91cbe31XXX",
               "type":"Single Outlet",
               "ip":"10.0.1.22"
            },
            {
               "name":"Coffee machine",
               "id":"23468277ecfabc9XXXXX",
               "key":"9ed8385ec455dXXX",
               "type":"Single Outlet",
               "ip":"10.0.1.23"
            },
            {
               "name":"Kettle",
               "id":"23468277807d3a7XXXXX",
               "key":"b4479775c250XXXX",
               "type":"Single Outlet",
               "ip":"10.0.1.24"
            }
         ]
      }
   ]
}
```

You didn't put the platform inside the `platforms` array property.

**Comment by bengpearson** [comment]
Thank you so much! all showing in the Home app now.

One more question - As below two of my plugs are showing offline despite showing as active in the other app. Here are my logs when starting Homebridge:

[03/01/2019, 19:47:05] [TuyaPlatform] Device has IP: 10.0.1.22
[03/01/2019, 19:47:05] [TuyaPlatform] New Device Online: Media center (21138270807d3a6xxxxx)
[03/01/2019, 19:47:05] [TuyaPlatform] Adding: Media center (generic / 21138270807d3a6xxxxx)
[03/01/2019, 19:47:05] [TuyaPlatform] Device has IP: 10.0.1.23
[03/01/2019, 19:47:05] [TuyaPlatform] New Device Online: Coffee machine (23468277ecfabc9xxxxx)
[03/01/2019, 19:47:05] [TuyaPlatform] Adding: Coffee machine (generic / 23468277ecfabc9xxxxx)
[03/01/2019, 19:47:05] [TuyaPlatform] Device has IP: 10.0.1.24
[03/01/2019, 19:47:05] [TuyaPlatform] New Device Online: Kettle (23468277807d3axxxxx)
[03/01/2019, 19:47:05] [TuyaPlatform] Adding: Kettle (generic / 23468277807d3axxxxx)
[03/01/2019, 19:47:05] Homebridge is running on port 51826.

Please find screenshot attached. Anything I can do to diagnose?

Thanks
![unadjustednonraw_thumb_4cc](https://user-images.githubusercontent.com/46249724/50658520-90787a00-0f91-11e9-95a6-09672d8ce7d5.jpg)

**Comment by codetheweb** [comment]
Try
1. Stop Homebridge.
2. Delete the `persist/` and `accessories/` directories in your Homebridge folder.
3. Start Homebridge again (with `DEBUG=* homebridge`).
4. Attempt to turn on/off a few unresponsive outlets and post the output.

**Comment by bengpearson** [comment]
Hi, all working now - I removed the 'ip' field - devices that had IP 10.0.1.22 and 10.0.1.23 were coming in on 1.30 and 1.34, so wondering if it was a DHCP issue. Thank you so much for your help!
