### ISSUE TITLE
Dimmer working nicely, but a bit slow on update

### ISSUE THREAD

**Issue by RikMuilwijk** [codetheweb/homebridge-tuya#44]
Wanted to confirm that this WiFi led dimmer switch: https://nl.aliexpress.com/item/Hot-WiFi-LED-Dimmer-220-v-110-v-Dimmen-Panel-Schakelaar-Aangesloten-op-Alexa-Google-Thuis/32910295055.html?spm=a2g0z.search0104.3.1.1edc55ebZaUZIK&transAbTest=ae803_5&ws_ab_test=searchweb0_0%2Csearchweb201602_1_10065_10068_319_317_10696_10084_453_10083_454_10618_10304_10307_10820_10821_10301_537_536_10902_10843_10059_10884_10887_321_322_10103%2Csearchweb201603_57%2CppcSwitch_0&algo_pvid=44a4e116-2614-4ae6-aa16-f1851bf490e3&algo_expid=44a4e116-2614-4ae6-aa16-f1851bf490e3-0

is working very nicely with this plugin, I've got the EU version. Waking up the dimmer goes very fast (instant), adjusting dimmer and turning off takes some time to get trough. Stumbled across this nice work whilst trying to get my mqtt topics right in OpenHAB, no luck on that sadly.

Is there a way I could resolve the command/state topics from this plugin? Somehow it does manage to talk to my switch 👍

**Comment by codetheweb** [comment]
What do you mean by command or state topics?

This doesn't act as a MQTT bridge, if that's what you're asking.

**Comment by RikMuilwijk** [comment]
I now see that this is not the right place for my MQTT question, clearly ;) Fixed my problem by moving on to another git

**Comment by codetheweb** [comment]
Alright, I'm closing this for now.

Free free to reopen this if you still have questions.
