### ISSUE TITLE
Powerstrip support

### ISSUE THREAD

**Issue by misanthrophy** [codetheweb/homebridge-tuya#48]
Hi,

Is this power strip fully supported by your app? 

https://s.click.aliexpress.com/e/2TerAfA

And if so, can I controll all outlets and usb ports insividually or only partially? 

Right now I am only using single outlets with this plugin so I am not sure how a config.jaon would look like in that case!

**Comment by codetheweb** [comment]
You should be able to control all ports individually if you set up your `config.json` properly.

Here's an example:

```javascript
...
"devices": [
    {
      "name": "Tuya Powerstrip 1",
      "id": "xxxxxxxxxxxxxxxxxxxx",
      "key": "xxxxxxxxxxxxxxxx",
      "options": {"dps": 1}
    },
    {
      "name": "Tuya Powerstrip 2",
      "id": "xxxxxxxxxxxxxxxxxxxx",
      "key": "xxxxxxxxxxxxxxxx",
      "options": {"dps": 2}
    }
  ]
...
```

Just copy and paste the 
```javascript
{
      "name": "Tuya Powerstrip 2",
      "id": "xxxxxxxxxxxxxxxxxxxx",
      "key": "xxxxxxxxxxxxxxxx",
      "options": {"dps": 2}
    }
```
for each controllable property, changing the `dps` option as you go.
