### ISSUE TITLE
Question : does this plugins uses the internet ?

### ISSUE THREAD

**Issue by nicolinuxfr** [codetheweb/homebridge-tuya#49]
Hello

It's more a general question than an issue really, sorry if it's the wrong channel.

HomeKit controls the connected devices locally and not via a server. It's a strength for speed and security reason, but of course, Homebridge can do thins differently.

It seems to me this plugin uses the Tuya API and thus needs an internet connexion to control the plugs. Am I mistaken ? Is it possible to control the devices using the Home app without any connexion and only locally ?

Thanks for your answer (and the plugin, of course) !

**Comment by codetheweb** [comment]
[TuyAPI](https://www.npmjs.com/package/tuyapi) (the protocol driver this plugin uses) does all communications with devices locally.  There is no code in TuyAPI that allows it to access Tuya's cloud servers.

**Comment by nicolinuxfr** [comment]
Great news, thanks for your answer !
