### ISSUE TITLE
0.43 version's plugin fail

### ISSUE THREAD

**Issue by kalety** [codetheweb/homebridge-tuya#51]
Good mornig from Spain! I've updated your plugin's version to 0.43 and don't work... I had to revert to 0.42 and 0 problems. This is the error:

Jun 24 10:43:47 COTO_IOT homebridge[8751]: (node:8751) UnhandledPromiseRejectionWarning: TypeError: this.device.find is not a function
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at new GenericAccessory (/usr/local/lib/node_modules/homebridge-tuya/lib/generic.js:35:14)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at TuyaPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tuya/index.js:84:27)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at TuyaDiscover.TuyaPlatform.discovery.on.device (/usr/local/lib/node_modules/homebridge-tuya/index.js:31:12)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at TuyaDiscover.emit (events.js:198:13)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at TuyaDiscover.startDiscovery (/usr/local/lib/node_modules/homebridge-tuya/lib/discovery.js:17:14)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at API.TuyaPlatform.api.on (/usr/local/lib/node_modules/homebridge-tuya/index.js:24:24)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at API.emit (events.js:203:15)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at startup (internal/bootstrap/node.js:283:19)
Jun 24 10:43:47 COTO_IOT homebridge[8751]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Jun 24 10:43:47 COTO_IOT homebridge[8751]: (node:8751) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jun 24 10:43:47 COTO_IOT homebridge[8751]: (node:8751) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by codetheweb** [comment]
I bumped the dependencies and published the update in v0.4.4.

I'm 80% sure that'll fix it, but if it doesn't please check out [this plugin](https://www.npmjs.com/package/homebridge-tuya-lan) instead as this one is deprecated.

**Comment by kalety** [comment]
Sorry, but...


Jun 26 10:50:01 COTO_IOT homebridge[27228]: [2019-6-26 10:50:01 AM] Error: Error from socket
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at Socket.emit (events.js:198:13)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jun 26 10:50:01 COTO_IOT homebridge[27228]: [2019-6-26 10:50:01 AM] Error: Error from socket
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at Socket.emit (events.js:198:13)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jun 26 10:50:01 COTO_IOT homebridge[27228]: [2019-6-26 10:50:01 AM] Error: Error from socket
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at Socket.emit (events.js:198:13)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 26 10:50:01 COTO_IOT homebridge[27228]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jun 26 10:50:01 COTO_IOT homebridge[27228]: [2019-6-26 10:50:01 AM] Got SIGTERM, shutting down Homebridge...
Jun 26 10:50:01 COTO_IOT homebridge[27228]: [2019-6-26 10:50:01 AM] [HarmonyHub] INFO - shutdown
Jun 26 10:50:02 COTO_IOT homebridge[27228]: [2019-6-26 10:50:02 AM] [Hue-alt] Philips hue: 10 accessories
Jun 26 10:50:02 COTO_IOT homebridge[27228]: [2019-6-26 10:50:02 AM] Error: Error from socket
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at Socket.emit (events.js:198:13)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jun 26 10:50:02 COTO_IOT homebridge[27228]: [2019-6-26 10:50:02 AM] Error: Error from socket
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at Socket.emit (events.js:198:13)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 26 10:50:02 COTO_IOT homebridge[27228]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jun 26 10:50:03 COTO_IOT homebridge[27228]: [2019-6-26 10:50:03 AM] [COTO_TV] webOS - Error: connect EHOSTUNREACH 192.168.1.19:3000
Jun 26 10:50:03 COTO_IOT homebridge[27228]: [2019-6-26 10:50:03 AM] Error: Error from socket
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at Socket.emit (events.js:198:13)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jun 26 10:50:03 COTO_IOT homebridge[27228]: [2019-6-26 10:50:03 AM] Error: Error from socket
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at Socket.client.on.err (/usr/local/lib/node_modules/homebridge-tuya/node_modules/tuyapi/index.js:323:30)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at Socket.emit (events.js:198:13)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 26 10:50:03 COTO_IOT homebridge[27228]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jun 26 10:50:03 COTO_IOT homebridge[27228]

**Comment by codetheweb** [comment]
I'm sorry that didn't work.

Because this plugin is deprecated I'm not offering support any more, I would recommend trying [this plugin](https://www.npmjs.com/package/homebridge-tuya-lan) instead.

**Comment by palla89** [comment]
Unfortunately, it seems that the creator of that plugin has stopped working on it :(
